/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.wdssii.gui.nbm.views;

import net.miginfocom.swing.MigLayout;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.wdssii.gui.views.WorldWindView;

@ConvertAsProperties(dtd = "-//org.wdssii.gui.nbm.views//Earth//EN",
autostore = false)
@TopComponent.Description(preferredID = "EarthTopComponent",
iconBase = "org/wdssii/gui/nbm/views/world.png",
persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "explorer", openAtStartup = true)
@ActionID(category = "Window", id = "org.wdssii.gui.nbm.views.EarthTopComponent")
@ActionReference(path = "Menu/Window/WDSSII" /*, position = 333 */)
@TopComponent.OpenActionRegistration(displayName = "#CTL_EarthAction",
preferredID = "EarthTopComponent")
/** Wrapper for a WorldWind 3D earth ball view
 * 
 * @author Robert Toomey
 */
public final class EarthTopComponent extends TopComponent {
   
    private WorldWindView myPanel;
    
    public EarthTopComponent() {
      //  initComponents();
        
        setLayout(new MigLayout("fill, inset 0", "", ""));
        myPanel = new WorldWindView();
        add(myPanel, "grow");
        
        setName(NbBundle.getMessage(EarthTopComponent.class, "CTL_EarthTopComponent"));
        setToolTipText(NbBundle.getMessage(EarthTopComponent.class, "HINT_EarthTopComponent")); 
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
 
}
