package org.wdssii.gui.nbm.views;

import net.miginfocom.swing.MigLayout;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.wdssii.gui.views.ProductsView;

@ConvertAsProperties(dtd = "-//org.wdssii.gui.nbm.views//ProductPicker//EN",
autostore = false)
@TopComponent.Description(preferredID = "ProductPickerTopComponent",
iconBase = "org/wdssii/gui/nbm/views/filter.gif",
persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "explorer", openAtStartup = true)
@ActionID(category = "Window", id = "org.wdssii.gui.nbm.views.ProductPickerTopComponent")
@ActionReference(path = "Menu/Window/WDSSII" /*, position = 333 */)
@TopComponent.OpenActionRegistration(displayName = "#CTL_ProductPickerAction",
preferredID = "ProductPickerTopComponent")
/** The Product picker is a view for choosing the data we want to view
 * out of the sources we have.  It's one of the most important views
 * 
 * @author Robert Toomey
 * 
 */
public final class ProductPickerTopComponent extends TopComponent  {
      
    private ProductsView myPanel;

    public ProductPickerTopComponent() {
        initComponents();
        
        setLayout(new MigLayout("fill, inset 0", "", ""));
        myPanel = new ProductsView();
        add(myPanel, "grow");

        setName(NbBundle.getMessage(ProductPickerTopComponent.class, "CTL_ProductPickerTopComponent"));
        setToolTipText(NbBundle.getMessage(ProductPickerTopComponent.class, "HINT_ProductPickerTopComponent"));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(300, 349));
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
 
}
