/*
 * LLHAreaSliceGUI.java
 *
 * @author Robert Toomey
 * 
 */
package org.wdssii.gui.volumes;

import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import org.wdssii.gui.CommandManager;
import org.wdssii.gui.LLHAreaManager;
import org.wdssii.gui.commands.LLHAreaChangeCommand;
import org.wdssii.gui.volumes.LLHArea.LLHAreaMemento;

/**
 * LLHAreaSliceGUI
 * 
 * The gui that appears in the 3D Object list when a LLHAreaSlice
 * is selected.  This allows controls for a LLHAreaSlice.
 * All 'common' controls are in the LLHAreaManager list, so for now at
 * least we'll have to recreate height controls for any subclass, but that's
 * ok since we might want different layout anyway.
 * 
 * @author Robert Toomey
 */
public class LLHAreaSliceGUI extends javax.swing.JPanel {

    private final LLHAreaSlice myOwner;

    /** Creates new form LLHAreaSliceGUI */
    public LLHAreaSliceGUI(LLHAreaSlice owner) {
        myOwner = owner;
        initComponents();
        String name = LLHAreaManager.getInstance().getVisibleName(owner);
        jNameLabel.setText(name);

        // Create a model for our max height spinner
        double maxHeight = myOwner.getTopHeightKms();
        double max = 20000;
        max = Math.max(20000, maxHeight);
        SpinnerModel model =
                new SpinnerNumberModel(maxHeight, //initial value
                0, //min  FIXME: get from LLHArea
                max, //max FIXME: get from LLHArea
                1); // 1 Meter step
        jMaxHeightKMS.setModel(model);
    }

    /** General update call */
    public void updateGUI() {
        String name = LLHAreaManager.getInstance().getVisibleName(myOwner);
        jNameLabel.setText(name);
        LLHAreaMemento m = myOwner.getMemento();
        jMaxHeightKMS.setValue(m.maxHeight);
        // Humm will round be an issue?
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jNameLabel = new javax.swing.JLabel();
        jMaxHeightKMS = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jNameLabel.setText(org.openide.util.NbBundle.getMessage(LLHAreaSliceGUI.class, "LLHAreaSliceGUI.jNameLabel.text")); // NOI18N
        add(jNameLabel);

        jMaxHeightKMS.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jMaxHeightKMSStateChanged(evt);
            }
        });
        add(jMaxHeightKMS);

        jLabel1.setText(org.openide.util.NbBundle.getMessage(LLHAreaSliceGUI.class, "LLHAreaSliceGUI.jLabel1.text")); // NOI18N
        add(jLabel1);
    }// </editor-fold>//GEN-END:initComponents

    private void jMaxHeightKMSStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jMaxHeightKMSStateChanged
        double value = (Double) jMaxHeightKMS.getValue();
        LLHAreaMemento m = myOwner.getMemento();
        m.useMaxHeight = true;
        m.maxHeight = value;
        LLHAreaChangeCommand c = new LLHAreaChangeCommand(myOwner, m);
        CommandManager.getInstance().executeCommand(c, true);
    }//GEN-LAST:event_jMaxHeightKMSStateChanged
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSpinner jMaxHeightKMS;
    private javax.swing.JLabel jNameLabel;
    // End of variables declaration//GEN-END:variables
}
